language: node_js
node_js:
  - "lts/*"

jobs:
  include:
    - stage: deploy
      before_deploy:
      - cd packages/cli
      deploy:
        provider: npm
        email: $NPM_USERNAME
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
